/**
 * ═══════════════════════════════════════════════════════════════════════════
 * 📌 ملخص توجيهي | Guiding Summary
 * ═══════════════════════════════════════════════════════════════════════════
 * 📄 الملف: schema-registry.ts
 * 📂 المسار: packages/plugins/src/canvas-designer/schema-registry.ts
 * 🎯 الهدف الرئيسي: سجل وتعريفات الـ 23 نوع عنصر لمصمم الكانفا والتحقق من صحتها.
 * 📋 المعايير:
 *    - تسجيل كامل للـ 23 Schema مع قيم افتراضية نقية وقيود دقيقة.
 *    - توفير دوال مساعدة للإنشاء والتحقق.
 * 🏷️ المعرف: PLUG-010
 * 📅 تاريخ الإنشاء: 2026-08-20
 * 🧠 الطريقة المبتكرة | Innovative Pattern:
 *    Immutable Canvas Element Registry with Strict Validation and Dynamic Factory Initializer.
 * ⚠️ نقاط الخطر الإلزامية | Mandatory Gotchas:
 *    1. الالتزام بحدود الأسطر (<400 سطر).
 * 👤 المالك: Hossam El-Din Abdel-Moaty El-Khouly - All rights reserved
 * ⚖️ الترخيص: MIT License
 * ═══════════════════════════════════════════════════════════════════════════
 */

import type {
  CanvasElementType,
  ElementSchemaDefinition,
  CanvasElementInstance,
} from './schema-types';

export const CANVAS_ELEMENT_SCHEMAS: Record<CanvasElementType, ElementSchemaDefinition> = {
  // 1. Basic Shapes
  rect: {
    type: 'rect',
    category: 'basic',
    nameAr: 'مستطيل',
    nameEn: 'Rectangle',
    defaultWidth: 140,
    defaultHeight: 80,
    minWidth: 20,
    minHeight: 20,
    defaultFill: '#f0f9ff',
    defaultStroke: '#0284c7',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  'rounded-rect': {
    type: 'rounded-rect',
    category: 'basic',
    nameAr: 'مستطيل مستدير الحواف',
    nameEn: 'Rounded Rectangle',
    defaultWidth: 150,
    defaultHeight: 80,
    minWidth: 20,
    minHeight: 20,
    defaultFill: '#f8fafc',
    defaultStroke: '#334155',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  circle: {
    type: 'circle',
    category: 'basic',
    nameAr: 'دائرة',
    nameEn: 'Circle',
    defaultWidth: 100,
    defaultHeight: 100,
    minWidth: 20,
    minHeight: 20,
    defaultFill: '#fffbeb',
    defaultStroke: '#d97706',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: false,
  },
  ellipse: {
    type: 'ellipse',
    category: 'basic',
    nameAr: 'شكل بيضاوي',
    nameEn: 'Ellipse',
    defaultWidth: 140,
    defaultHeight: 90,
    minWidth: 30,
    minHeight: 20,
    defaultFill: '#fefce8',
    defaultStroke: '#ca8a04',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  triangle: {
    type: 'triangle',
    category: 'basic',
    nameAr: 'مثلث',
    nameEn: 'Triangle',
    defaultWidth: 120,
    defaultHeight: 100,
    minWidth: 20,
    minHeight: 20,
    defaultFill: '#fff1f2',
    defaultStroke: '#e11d48',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  diamond: {
    type: 'diamond',
    category: 'basic',
    nameAr: 'معين / قرار',
    nameEn: 'Diamond',
    defaultWidth: 130,
    defaultHeight: 90,
    minWidth: 30,
    minHeight: 30,
    defaultFill: '#f0fdf4',
    defaultStroke: '#16a34a',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },

  // 2. Advanced Polygons & Stars
  parallelogram: {
    type: 'parallelogram',
    category: 'polygon',
    nameAr: 'متوازي أضلاع',
    nameEn: 'Parallelogram',
    defaultWidth: 140,
    defaultHeight: 80,
    minWidth: 30,
    minHeight: 20,
    defaultFill: '#faf5ff',
    defaultStroke: '#9333ea',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  trapezoid: {
    type: 'trapezoid',
    category: 'polygon',
    nameAr: 'شبه منحرف',
    nameEn: 'Trapezoid',
    defaultWidth: 140,
    defaultHeight: 80,
    minWidth: 30,
    minHeight: 20,
    defaultFill: '#fdf4ff',
    defaultStroke: '#c026d3',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  cylinder: {
    type: 'cylinder',
    category: 'polygon',
    nameAr: 'أسطوانة قاعدة بيانات',
    nameEn: 'Cylinder / DB',
    defaultWidth: 110,
    defaultHeight: 120,
    minWidth: 40,
    minHeight: 40,
    defaultFill: '#ecfeff',
    defaultStroke: '#0891b2',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  star: {
    type: 'star',
    category: 'polygon',
    nameAr: 'نجمة خماسية',
    nameEn: 'Star',
    defaultWidth: 110,
    defaultHeight: 110,
    minWidth: 30,
    minHeight: 30,
    defaultFill: '#fffbeb',
    defaultStroke: '#f59e0b',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },

  // 3. Flowchart & Architecture Blocks
  'flowchart-process': {
    type: 'flowchart-process',
    category: 'flowchart',
    nameAr: 'عملية تدفقية',
    nameEn: 'Process Block',
    defaultWidth: 160,
    defaultHeight: 70,
    minWidth: 40,
    minHeight: 30,
    defaultFill: '#f0fdfa',
    defaultStroke: '#0d9488',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  'flowchart-decision': {
    type: 'flowchart-decision',
    category: 'flowchart',
    nameAr: 'شرط وتحقق',
    nameEn: 'Decision Block',
    defaultWidth: 140,
    defaultHeight: 90,
    minWidth: 40,
    minHeight: 40,
    defaultFill: '#fef3c7',
    defaultStroke: '#d97706',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  'flowchart-data': {
    type: 'flowchart-data',
    category: 'flowchart',
    nameAr: 'مدخلات / بيانات',
    nameEn: 'Data Block',
    defaultWidth: 150,
    defaultHeight: 75,
    minWidth: 40,
    minHeight: 30,
    defaultFill: '#e0e7ff',
    defaultStroke: '#4f46e5',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  cloud: {
    type: 'cloud',
    category: 'flowchart',
    nameAr: 'سحابة وخدمات خارجية',
    nameEn: 'Cloud Service',
    defaultWidth: 160,
    defaultHeight: 95,
    minWidth: 60,
    minHeight: 40,
    defaultFill: '#f1f5f9',
    defaultStroke: '#475569',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  actor: {
    type: 'actor',
    category: 'flowchart',
    nameAr: 'مستخدم / ممثل النظام (Actor)',
    nameEn: 'System Actor',
    defaultWidth: 80,
    defaultHeight: 120,
    minWidth: 40,
    minHeight: 60,
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: false,
  },

  // 4. Text, Media & Sticky
  text: {
    type: 'text',
    category: 'text-media',
    nameAr: 'كتلة نصية',
    nameEn: 'Text Block',
    defaultWidth: 140,
    defaultHeight: 40,
    minWidth: 20,
    minHeight: 20,
    defaultFill: 'transparent',
    defaultStroke: 'transparent',
    defaultStrokeWidth: 0,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  'sticky-note': {
    type: 'sticky-note',
    category: 'text-media',
    nameAr: 'ملاحظة لاصقة (Sticky Note)',
    nameEn: 'Sticky Note',
    defaultWidth: 140,
    defaultHeight: 140,
    minWidth: 50,
    minHeight: 50,
    defaultFill: '#fef08a',
    defaultStroke: '#eab308',
    defaultStrokeWidth: 1,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  callout: {
    type: 'callout',
    category: 'text-media',
    nameAr: 'فقاعة حوارية (Callout)',
    nameEn: 'Callout Speech Bubble',
    defaultWidth: 150,
    defaultHeight: 90,
    minWidth: 40,
    minHeight: 30,
    defaultFill: '#ffffff',
    defaultStroke: '#64748b',
    defaultStrokeWidth: 2,
    hasText: true,
    resizable: true,
    rotatable: true,
  },
  'image-frame': {
    type: 'image-frame',
    category: 'text-media',
    nameAr: 'إطار صورة / وسائط',
    nameEn: 'Image Frame',
    defaultWidth: 180,
    defaultHeight: 130,
    minWidth: 40,
    minHeight: 40,
    defaultFill: '#f8fafc',
    defaultStroke: '#cbd5e1',
    defaultStrokeWidth: 1.5,
    hasText: false,
    resizable: true,
    rotatable: true,
  },

  // 5. Paths, Connectors & Containers
  'freehand-path': {
    type: 'freehand-path',
    category: 'connector-group',
    nameAr: 'مسار حر باليد (Pencil)',
    nameEn: 'Freehand Path',
    defaultWidth: 100,
    defaultHeight: 100,
    minWidth: 10,
    minHeight: 10,
    defaultFill: 'none',
    defaultStroke: '#0284c7',
    defaultStrokeWidth: 2.5,
    hasText: false,
    resizable: true,
    rotatable: true,
  },
  'bezier-curve': {
    type: 'bezier-curve',
    category: 'connector-group',
    nameAr: 'منحنى بيزييه متجهي',
    nameEn: 'Bezier Curve',
    defaultWidth: 150,
    defaultHeight: 100,
    minWidth: 20,
    minHeight: 20,
    defaultFill: 'none',
    defaultStroke: '#0284c7',
    defaultStrokeWidth: 2,
    hasText: false,
    resizable: true,
    rotatable: true,
  },
  'smart-connector': {
    type: 'smart-connector',
    category: 'connector-group',
    nameAr: 'وصلة ذكية برؤوس أسهم',
    nameEn: 'Smart Connector',
    defaultWidth: 120,
    defaultHeight: 60,
    minWidth: 10,
    minHeight: 10,
    defaultFill: 'none',
    defaultStroke: '#0284c7',
    defaultStrokeWidth: 2,
    hasText: false,
    resizable: false,
    rotatable: false,
  },
  'group-container': {
    type: 'group-container',
    category: 'connector-group',
    nameAr: 'حاوية تجميع (Group Container)',
    nameEn: 'Group Container',
    defaultWidth: 200,
    defaultHeight: 150,
    minWidth: 40,
    minHeight: 40,
    defaultFill: 'transparent',
    defaultStroke: '#94a3b8',
    defaultStrokeWidth: 1,
    hasText: true,
    resizable: true,
    rotatable: false,
    isContainer: true,
  },
};

export function getSchemaForType(type: CanvasElementType): ElementSchemaDefinition {
  return CANVAS_ELEMENT_SCHEMAS[type] || CANVAS_ELEMENT_SCHEMAS.rect;
}

export function getAllSchemas(): ElementSchemaDefinition[] {
  return Object.values(CANVAS_ELEMENT_SCHEMAS);
}

export function createDefaultElement(
  id: string,
  type: CanvasElementType,
  x: number,
  y: number,
  zIndex: number = 0,
): CanvasElementInstance {
  const schema = getSchemaForType(type);
  return {
    id,
    type,
    x,
    y,
    width: schema.defaultWidth,
    height: schema.defaultHeight,
    zIndex,
    text: schema.hasText ? schema.nameAr : undefined,
    fill: schema.defaultFill,
    stroke: schema.defaultStroke,
    strokeWidth: schema.defaultStrokeWidth,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
  };
}
